# Generated by Django 4.1.7 on 2023-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
