# Generated by Django 4.1.7 on 2023-03-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registation', '0005_alter_profilemodel_photo_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
