# Generated by Django 4.1.7 on 2023-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registation', '0006_delete_profilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('photo_profile', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
